### ISSUE TITLE
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `plugins: [jekyll-paginate]` in your configuration file.

### ISSUE THREAD

**Issue by ValchanOficial** [ValchanOficial/valchan#1]
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `plugins: [jekyll-paginate]` in your configuration file.

**Comment by ValchanOficial** [comment]
1º - Instale a gem no terminal:
`gem install jekyll-paginate`

-----------------------------

2º - Dentro do **_config.yml**:
```
plugins:
  - jekyll-paginate
paginate: 5
```

-----------------------------

3º - Dentro do ***Gemfile**:
```
group :jekyll_plugins do
   gem "jekyll-paginate"
end
```

**Comment by huangli** [comment]
1. Add jekyll-paginate in Gemfile file
`group :jekyll_plugins do
  gem "jekyll-paginate"
end`

2. install gem 
`bundle install
`
